BulkyBookWebApp/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.CoverTypeRepositories;
using BulkyBook.DataAccess.Repository.UnitofWork;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace BulkyBookWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitofWork _db;

        public CoverTypeController(IUnitofWork db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<CoverType> ObjectCoverTypeList = _db.CoverType.GetAll();
            return View(ObjectCoverTypeList);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType cat)
        {
            if (ModelState.IsValid)
            {
                _db.CoverType.Add(cat);
                _db.Save();
                return RedirectToAction("Index");
            }
            return View(cat);


        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CoverTypefromdb = _db.CoverType.GetFirstorDefault(c => c.Id == id);
            return View(CoverTypefromdb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType cat)
        {
            if (ModelState.IsValid)
            {
                _db.CoverType.Update(cat);
                _db.Save();
                return RedirectToAction("Index");
            }
            return View(cat);


        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CoverTypefromdb = _db.CoverType.GetFirstorDefault(c => c.Id == id);
            return View(CoverTypefromdb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var idfromdb = _db.CoverType.GetFirstorDefault(c => c.Id == id);
            if (idfromdb == null)
            {
                return NotFound();
            }
            _db.CoverType.Remove(idfromdb);
            _db.Save();
            return RedirectToAction("Index");
        }
    }
}

BulkyBookWebApp/Areas/Admin/Views/CoverType/Create.cshtml
@model BulkyBook.Models.CoverType



<form method="POST">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Create CoverType
            </h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-action="Index" asp-controller="CoverType" class="btn btn-secondary" style="width:150px">Go Back to List</a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BulkyBookWebApp/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType


<form method="POST" asp-action="DeletePOST">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Delete CoverType
            </h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
        <a asp-action="Index" asp-controller="CoverType" class="btn btn-secondary" style="width:150px">Go Back to List</a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BulkyBookWebApp/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType


<form method="POST">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Edit CoverType
            </h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-action="Index" asp-controller="CoverType" class="btn btn-secondary" style="width:150px">Go Back to List</a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BulkyBookWebApp/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<BulkyBook.Models.CoverType>
@{
    ViewData["Title"] = "Index";
}


<div class="Container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">CoverType List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-action="Create" asp-controller="CoverType" class="btn btn-primary">
                Create New CoverType
            </a>
        </div>
    </div>


<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Cover Type
            </th>
            <th>

            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width="50%">
                    @item.Name
                </td>
                <td class="text-end">
                    <div class="w-50 btn-group text-end" role="group">
                        <a asp-action="Edit" asp-controller="CoverType" asp-route-id="@item.Id" class="btn btn-primary mx-2">Edit</a>
                    </div>
                </td>
                <td class="text-end">
                    <div class="w-50 btn-group text-end" role="group">
                        <a asp-action="Delete" asp-controller="CoverType" asp-route-id="@item.Id" class="btn btn-primary mx-2">Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>